In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("twitter_train.csv",delimiter = ",")

In [3]:
x_text = data["text"]

In [4]:
set(data["airline_sentiment"])

{'negative', 'neutral', 'positive'}

In [5]:
data.head()

,tweet_id,airline_sentiment,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,5.679000e+17,negative,Southwest,NaN,ColeyGirouard,NaN,0,"@SouthwestAir I am scheduled for the morning, ...",NaN,17-02-2015 20:16,Washington D.C.,Atlantic Time (Canada)
1,5.699890e+17,positive,Southwest,NaN,WalterFaddoul,NaN,0,@SouthwestAir seeing your workers time in and ...,NaN,23-02-2015 14:36,"Indianapolis, Indiana; USA",Central Time (US & Canada)
2,5.680890e+17,positive,United,NaN,LocalKyle,NaN,0,@united Flew ORD to Miami and back and had gr...,NaN,18-02-2015 08:46,Illinois,Central Time (US & Canada)
3,5.689280e+17,negative,Southwest,NaN,amccarthy19,NaN,0,@SouthwestAir @dultch97 that's horse radish üò§üê¥,NaN,20-02-2015 16:20,NaN,Atlantic Time (Canada)
4,5.685940e+17,negative,United,NaN,J_Okayy,NaN,0,@united so our flight into ORD was delayed bec...,NaN,19-02-2015 18:13,NaN,Eastern Time (US & Canada)

In [6]:
x_text = list(x_text)

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
count_vec = CountVectorizer(max_df = 0.9, min_df = 0.001, ngram_range = (1,2))
x_train = count_vec.fit_transform(x_text)
x_train.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [9]:
x_train.shape

(10980, 3336)

In [10]:
def change_to_numeric(sentiment):
    if sentiment == 'negative':
        return 0
    elif sentiment == 'neutral':
        return 1
    else:
        return 2

In [11]:
y_train_labelled = list(data["airline_sentiment"])
y_train = []
for i in y_train_labelled:
    y_train.append(change_to_numeric(i))
y_train

[0,
 2,
 2,
 0,
 0,
 0,
 0,
 2,
 0,
 2,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 1,
 0,
 0,
 2,
 2,
 0,
 2,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 2,
 0,
 0,
 0,
 1,
 2,
 2,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 2,
 2,
 0,
 0,
 1,
 2,
 1,
 0,
 0,
 1,
 0,
 0,
 2,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 2,
 2,
 0,
 1,
 2,
 0,
 0,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 2,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 2,
 0,
 2,
 2,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 2,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 2,
 1,
 2,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 1,
 0,
 0,
 1,
 2,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 2,
 0,
 2,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 2,
 0,
 1,
 0,
 0,
 2,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 2,
 0,
 0,
 1,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 1,
 0,
 0,
 2,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 2,
 0,
 0,
 0,
 2,
 2,
 0,
 1,
 0,
 0,
 2,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 1,
 0,
 0,
 0,
 1,
 2,
 0,
 2,
 2,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 2,
 1,
 1,
 1,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 1,
 2,
 0,
 0,
 1,
 2,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 1,
 0,
 0,
 1,
 2,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 2,
 0,
 0,
 1,
 0,
 2,
 0,
 1,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 1,
 0,
 2,
 0,
 0,
 2,
 0,
 0,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 2,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 2,
 0,
 2,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 1,
 0,
 2,
 0,
 2,
 0,
 0,
 2,
 0,
 1,
 1,
 0,
 0,
 2,
 1,
 1,
 2,
 2,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 2,
 0,
 1,
 0,
 0,
 0,
 2,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 1,
 0,
 1,
 0,
 0,
 0,
 2,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 1,
 0,
 1,
 1,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 2,
 2,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 0,
 2,
 1,
 0,
 2,
 1,
 0,
 0,
 2,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 2,
 2,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 2,
 0,
 2,
 0,
 0,
 2,
 0,
 2,
 0,
 0,
 1,
 1,
 2,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 2,
 1,
 0,
 0,
 2,
 1,
 0,
 0,
 2,
 1,
 0,
 2,
 1,
 0,
 0,
 2,
 0,
 2,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 2,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 2,
 0,
 0,
 1,
 0,
 1,
 2,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 2,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 2,
 0,
 1,
 0,
 0,
 2,
 2,
 1,
 2,
 1,
 0,
 2,
 2,
 0,
 1,
 0,
 1,
 0,
 0,
 2,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 2,
 1,
 2,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 ...]

In [12]:
x_train = x_train.todense()

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_TRAIN,X_TEST,Y_TRAIN,Y_TEST = train_test_split(x_train,y_train,random_state = 0)

In [15]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB(alpha = 0.1)
clf.fit(X_TRAIN,Y_TRAIN)

MultinomialNB(alpha=0.1, class_prior=None, fit_prior=True)

In [16]:
clf.score(X_TEST,Y_TEST)

0.7766848816029144

In [17]:
from sklearn.svm import SVC
clf = SVC()
clf.fit(X_TRAIN,Y_TRAIN)

C:\Users\Shivu Arun\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [18]:
clf.score(X_TEST,Y_TEST)

0.6335154826958106

In [19]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(X_TRAIN,Y_TRAIN)

C:\Users\Shivu Arun\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [20]:
clf.score(X_TEST,Y_TEST)

0.7351548269581056

In [21]:
def change_to_labelled(sentiment):
    if sentiment == 0:
        return 'negative'
    elif sentiment == 1:
        return 'neutral'
    else:
        return 'positive'

In [22]:
testing_data = pd.read_csv("twitter_test.csv",delimiter = ',')

In [23]:
testing_data.head()

,tweet_id,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,5.696820e+17,American,NaN,zsalim03,NaN,0,@AmericanAir In car gng to DFW. Pulled over 1h...,NaN,22-02-2015 18:15,Texas,Central Time (US & Canada)
1,5.696080e+17,American,NaN,sa_craig,NaN,0,"@AmericanAir after all, the plane didn‚Äôt land ...",NaN,22-02-2015 13:22,"College Station, TX",Central Time (US & Canada)
2,5.678790e+17,Southwest,NaN,DanaChristos,NaN,1,@SouthwestAir can't believe how many paying cu...,NaN,17-02-2015 18:52,CT,Eastern Time (US & Canada)
3,5.697580e+17,US Airways,NaN,rossj987,NaN,0,@USAirways I can legitimately say that I would...,NaN,22-02-2015 23:16,"Washington, D.C.",Eastern Time (US & Canada)
4,5.699010e+17,American,NaN,tranpham18,NaN,0,@AmericanAir still no response from AA. great ...,NaN,23-02-2015 08:44,New York City,Eastern Time (US & Canada)

In [24]:
test_text = testing_data["text"]

In [25]:
x_test = count_vec.transform(test_text)
x_test = x_test.todense()

In [26]:
clf = MultinomialNB(alpha = 0.1)
clf.fit(x_train,y_train)

MultinomialNB(alpha=0.1, class_prior=None, fit_prior=True)

In [285]:
clf.score(x_train,y_train)

0.8360655737704918

In [286]:
pred = clf.predict(x_test)

In [289]:
submission_values = []
for i in pred:
    submission_values.append(change_to_labelled(i))

In [293]:
np.savetxt("twitterout.csv",submission_values,fmt="%s")

In [27]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier()
clf.fit(X_TRAIN,Y_TRAIN)
clf.score(X_TEST,Y_TEST)

0.760655737704918